# Setup
title: La isla del SOOOOL 
#email: noniadas@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 MI LUNA EN PISCIS Y SOL MAYOR 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: SolCatv2
github_username:  suflorcita

# Build settings
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
